-- https://school.programmers.co.kr/learn/courses/30/lessons/59413
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)
SELECT 
    H.HOUR AS HOUR,
    COUNT(a.DATETIME) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS A
    ON HOUR(A.DATETIME) = H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR;